/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPtRouteImport } from './routes/_authenticated/pt'
import { Route as AuthenticatedPtIndexRouteImport } from './routes/_authenticated/pt.index'
import { Route as AuthenticatedPtTrainingsRouteImport } from './routes/_authenticated/pt.trainings'
import { Route as AuthenticatedPtReportsRouteImport } from './routes/_authenticated/pt.reports'
import { Route as AuthenticatedPtPaymentsRouteImport } from './routes/_authenticated/pt.payments'
import { Route as AuthenticatedPtClientsRouteImport } from './routes/_authenticated/pt.clients'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtRoute = AuthenticatedPtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtIndexRoute = AuthenticatedPtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedPtTrainingsRoute =
  AuthenticatedPtTrainingsRouteImport.update({
    id: '/trainings',
    path: '/trainings',
    getParentRoute: () => AuthenticatedPtRoute,
  } as any)
const AuthenticatedPtReportsRoute = AuthenticatedPtReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedPtPaymentsRoute = AuthenticatedPtPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedPtClientsRoute = AuthenticatedPtClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/pt': typeof AuthenticatedPtRouteWithChildren
  '/pt/clients': typeof AuthenticatedPtClientsRoute
  '/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/pt/reports': typeof AuthenticatedPtReportsRoute
  '/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/pt/': typeof AuthenticatedPtIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/pt/clients': typeof AuthenticatedPtClientsRoute
  '/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/pt/reports': typeof AuthenticatedPtReportsRoute
  '/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/pt': typeof AuthenticatedPtIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/pt': typeof AuthenticatedPtRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pt/clients': typeof AuthenticatedPtClientsRoute
  '/_authenticated/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/_authenticated/pt/reports': typeof AuthenticatedPtReportsRoute
  '/_authenticated/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/_authenticated/pt/': typeof AuthenticatedPtIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pt'
    | '/pt/clients'
    | '/pt/payments'
    | '/pt/reports'
    | '/pt/trainings'
    | '/pt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/pt/clients'
    | '/pt/payments'
    | '/pt/reports'
    | '/pt/trainings'
    | '/pt'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/pt'
    | '/_authenticated/'
    | '/_authenticated/pt/clients'
    | '/_authenticated/pt/payments'
    | '/_authenticated/pt/reports'
    | '/_authenticated/pt/trainings'
    | '/_authenticated/pt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pt': {
      id: '/_authenticated/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof AuthenticatedPtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pt/': {
      id: '/_authenticated/pt/'
      path: '/'
      fullPath: '/pt/'
      preLoaderRoute: typeof AuthenticatedPtIndexRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/trainings': {
      id: '/_authenticated/pt/trainings'
      path: '/trainings'
      fullPath: '/pt/trainings'
      preLoaderRoute: typeof AuthenticatedPtTrainingsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/reports': {
      id: '/_authenticated/pt/reports'
      path: '/reports'
      fullPath: '/pt/reports'
      preLoaderRoute: typeof AuthenticatedPtReportsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/payments': {
      id: '/_authenticated/pt/payments'
      path: '/payments'
      fullPath: '/pt/payments'
      preLoaderRoute: typeof AuthenticatedPtPaymentsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/clients': {
      id: '/_authenticated/pt/clients'
      path: '/clients'
      fullPath: '/pt/clients'
      preLoaderRoute: typeof AuthenticatedPtClientsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
  }
}

interface AuthenticatedPtRouteChildren {
  AuthenticatedPtClientsRoute: typeof AuthenticatedPtClientsRoute
  AuthenticatedPtPaymentsRoute: typeof AuthenticatedPtPaymentsRoute
  AuthenticatedPtReportsRoute: typeof AuthenticatedPtReportsRoute
  AuthenticatedPtTrainingsRoute: typeof AuthenticatedPtTrainingsRoute
  AuthenticatedPtIndexRoute: typeof AuthenticatedPtIndexRoute
}

const AuthenticatedPtRouteChildren: AuthenticatedPtRouteChildren = {
  AuthenticatedPtClientsRoute: AuthenticatedPtClientsRoute,
  AuthenticatedPtPaymentsRoute: AuthenticatedPtPaymentsRoute,
  AuthenticatedPtReportsRoute: AuthenticatedPtReportsRoute,
  AuthenticatedPtTrainingsRoute: AuthenticatedPtTrainingsRoute,
  AuthenticatedPtIndexRoute: AuthenticatedPtIndexRoute,
}

const AuthenticatedPtRouteWithChildren = AuthenticatedPtRoute._addFileChildren(
  AuthenticatedPtRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedPtRoute: typeof AuthenticatedPtRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPtRoute: AuthenticatedPtRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
