/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPtRouteImport } from './routes/_authenticated/pt'
import { Route as AuthenticatedImobiliarioRouteImport } from './routes/_authenticated/imobiliario'
import { Route as AuthenticatedFinancasRouteImport } from './routes/_authenticated/financas'
import { Route as AuthenticatedPtIndexRouteImport } from './routes/_authenticated/pt.index'
import { Route as AuthenticatedImobiliarioIndexRouteImport } from './routes/_authenticated/imobiliario.index'
import { Route as AuthenticatedFinancasIndexRouteImport } from './routes/_authenticated/financas.index'
import { Route as ApiPublicImoveisScrapeRouteImport } from './routes/api/public/imoveis-scrape'
import { Route as AuthenticatedPtTrainingsRouteImport } from './routes/_authenticated/pt.trainings'
import { Route as AuthenticatedPtReportsRouteImport } from './routes/_authenticated/pt.reports'
import { Route as AuthenticatedPtPaymentsRouteImport } from './routes/_authenticated/pt.payments'
import { Route as AuthenticatedPtClientsRouteImport } from './routes/_authenticated/pt.clients'
import { Route as AuthenticatedImobiliarioConfigRouteImport } from './routes/_authenticated/imobiliario.config'
import { Route as AuthenticatedFinancasVariaveisRouteImport } from './routes/_authenticated/financas.variaveis'
import { Route as AuthenticatedFinancasFixasRouteImport } from './routes/_authenticated/financas.fixas'
import { Route as AuthenticatedFinancasCategoriasRouteImport } from './routes/_authenticated/financas.categorias'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtRoute = AuthenticatedPtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImobiliarioRoute =
  AuthenticatedImobiliarioRouteImport.update({
    id: '/imobiliario',
    path: '/imobiliario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancasRoute = AuthenticatedFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtIndexRoute = AuthenticatedPtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedImobiliarioIndexRoute =
  AuthenticatedImobiliarioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImobiliarioRoute,
  } as any)
const AuthenticatedFinancasIndexRoute =
  AuthenticatedFinancasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinancasRoute,
  } as any)
const ApiPublicImoveisScrapeRoute = ApiPublicImoveisScrapeRouteImport.update({
  id: '/api/public/imoveis-scrape',
  path: '/api/public/imoveis-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPtTrainingsRoute =
  AuthenticatedPtTrainingsRouteImport.update({
    id: '/trainings',
    path: '/trainings',
    getParentRoute: () => AuthenticatedPtRoute,
  } as any)
const AuthenticatedPtReportsRoute = AuthenticatedPtReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedPtPaymentsRoute = AuthenticatedPtPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedPtClientsRoute = AuthenticatedPtClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedPtRoute,
} as any)
const AuthenticatedImobiliarioConfigRoute =
  AuthenticatedImobiliarioConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedImobiliarioRoute,
  } as any)
const AuthenticatedFinancasVariaveisRoute =
  AuthenticatedFinancasVariaveisRouteImport.update({
    id: '/variaveis',
    path: '/variaveis',
    getParentRoute: () => AuthenticatedFinancasRoute,
  } as any)
const AuthenticatedFinancasFixasRoute =
  AuthenticatedFinancasFixasRouteImport.update({
    id: '/fixas',
    path: '/fixas',
    getParentRoute: () => AuthenticatedFinancasRoute,
  } as any)
const AuthenticatedFinancasCategoriasRoute =
  AuthenticatedFinancasCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedFinancasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/financas': typeof AuthenticatedFinancasRouteWithChildren
  '/imobiliario': typeof AuthenticatedImobiliarioRouteWithChildren
  '/pt': typeof AuthenticatedPtRouteWithChildren
  '/financas/categorias': typeof AuthenticatedFinancasCategoriasRoute
  '/financas/fixas': typeof AuthenticatedFinancasFixasRoute
  '/financas/variaveis': typeof AuthenticatedFinancasVariaveisRoute
  '/imobiliario/config': typeof AuthenticatedImobiliarioConfigRoute
  '/pt/clients': typeof AuthenticatedPtClientsRoute
  '/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/pt/reports': typeof AuthenticatedPtReportsRoute
  '/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/api/public/imoveis-scrape': typeof ApiPublicImoveisScrapeRoute
  '/financas/': typeof AuthenticatedFinancasIndexRoute
  '/imobiliario/': typeof AuthenticatedImobiliarioIndexRoute
  '/pt/': typeof AuthenticatedPtIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/financas/categorias': typeof AuthenticatedFinancasCategoriasRoute
  '/financas/fixas': typeof AuthenticatedFinancasFixasRoute
  '/financas/variaveis': typeof AuthenticatedFinancasVariaveisRoute
  '/imobiliario/config': typeof AuthenticatedImobiliarioConfigRoute
  '/pt/clients': typeof AuthenticatedPtClientsRoute
  '/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/pt/reports': typeof AuthenticatedPtReportsRoute
  '/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/api/public/imoveis-scrape': typeof ApiPublicImoveisScrapeRoute
  '/financas': typeof AuthenticatedFinancasIndexRoute
  '/imobiliario': typeof AuthenticatedImobiliarioIndexRoute
  '/pt': typeof AuthenticatedPtIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/financas': typeof AuthenticatedFinancasRouteWithChildren
  '/_authenticated/imobiliario': typeof AuthenticatedImobiliarioRouteWithChildren
  '/_authenticated/pt': typeof AuthenticatedPtRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/financas/categorias': typeof AuthenticatedFinancasCategoriasRoute
  '/_authenticated/financas/fixas': typeof AuthenticatedFinancasFixasRoute
  '/_authenticated/financas/variaveis': typeof AuthenticatedFinancasVariaveisRoute
  '/_authenticated/imobiliario/config': typeof AuthenticatedImobiliarioConfigRoute
  '/_authenticated/pt/clients': typeof AuthenticatedPtClientsRoute
  '/_authenticated/pt/payments': typeof AuthenticatedPtPaymentsRoute
  '/_authenticated/pt/reports': typeof AuthenticatedPtReportsRoute
  '/_authenticated/pt/trainings': typeof AuthenticatedPtTrainingsRoute
  '/api/public/imoveis-scrape': typeof ApiPublicImoveisScrapeRoute
  '/_authenticated/financas/': typeof AuthenticatedFinancasIndexRoute
  '/_authenticated/imobiliario/': typeof AuthenticatedImobiliarioIndexRoute
  '/_authenticated/pt/': typeof AuthenticatedPtIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/financas'
    | '/imobiliario'
    | '/pt'
    | '/financas/categorias'
    | '/financas/fixas'
    | '/financas/variaveis'
    | '/imobiliario/config'
    | '/pt/clients'
    | '/pt/payments'
    | '/pt/reports'
    | '/pt/trainings'
    | '/api/public/imoveis-scrape'
    | '/financas/'
    | '/imobiliario/'
    | '/pt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/financas/categorias'
    | '/financas/fixas'
    | '/financas/variaveis'
    | '/imobiliario/config'
    | '/pt/clients'
    | '/pt/payments'
    | '/pt/reports'
    | '/pt/trainings'
    | '/api/public/imoveis-scrape'
    | '/financas'
    | '/imobiliario'
    | '/pt'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/financas'
    | '/_authenticated/imobiliario'
    | '/_authenticated/pt'
    | '/_authenticated/'
    | '/_authenticated/financas/categorias'
    | '/_authenticated/financas/fixas'
    | '/_authenticated/financas/variaveis'
    | '/_authenticated/imobiliario/config'
    | '/_authenticated/pt/clients'
    | '/_authenticated/pt/payments'
    | '/_authenticated/pt/reports'
    | '/_authenticated/pt/trainings'
    | '/api/public/imoveis-scrape'
    | '/_authenticated/financas/'
    | '/_authenticated/imobiliario/'
    | '/_authenticated/pt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicImoveisScrapeRoute: typeof ApiPublicImoveisScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pt': {
      id: '/_authenticated/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof AuthenticatedPtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imobiliario': {
      id: '/_authenticated/imobiliario'
      path: '/imobiliario'
      fullPath: '/imobiliario'
      preLoaderRoute: typeof AuthenticatedImobiliarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financas': {
      id: '/_authenticated/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof AuthenticatedFinancasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pt/': {
      id: '/_authenticated/pt/'
      path: '/'
      fullPath: '/pt/'
      preLoaderRoute: typeof AuthenticatedPtIndexRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/imobiliario/': {
      id: '/_authenticated/imobiliario/'
      path: '/'
      fullPath: '/imobiliario/'
      preLoaderRoute: typeof AuthenticatedImobiliarioIndexRouteImport
      parentRoute: typeof AuthenticatedImobiliarioRoute
    }
    '/_authenticated/financas/': {
      id: '/_authenticated/financas/'
      path: '/'
      fullPath: '/financas/'
      preLoaderRoute: typeof AuthenticatedFinancasIndexRouteImport
      parentRoute: typeof AuthenticatedFinancasRoute
    }
    '/api/public/imoveis-scrape': {
      id: '/api/public/imoveis-scrape'
      path: '/api/public/imoveis-scrape'
      fullPath: '/api/public/imoveis-scrape'
      preLoaderRoute: typeof ApiPublicImoveisScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pt/trainings': {
      id: '/_authenticated/pt/trainings'
      path: '/trainings'
      fullPath: '/pt/trainings'
      preLoaderRoute: typeof AuthenticatedPtTrainingsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/reports': {
      id: '/_authenticated/pt/reports'
      path: '/reports'
      fullPath: '/pt/reports'
      preLoaderRoute: typeof AuthenticatedPtReportsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/payments': {
      id: '/_authenticated/pt/payments'
      path: '/payments'
      fullPath: '/pt/payments'
      preLoaderRoute: typeof AuthenticatedPtPaymentsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/pt/clients': {
      id: '/_authenticated/pt/clients'
      path: '/clients'
      fullPath: '/pt/clients'
      preLoaderRoute: typeof AuthenticatedPtClientsRouteImport
      parentRoute: typeof AuthenticatedPtRoute
    }
    '/_authenticated/imobiliario/config': {
      id: '/_authenticated/imobiliario/config'
      path: '/config'
      fullPath: '/imobiliario/config'
      preLoaderRoute: typeof AuthenticatedImobiliarioConfigRouteImport
      parentRoute: typeof AuthenticatedImobiliarioRoute
    }
    '/_authenticated/financas/variaveis': {
      id: '/_authenticated/financas/variaveis'
      path: '/variaveis'
      fullPath: '/financas/variaveis'
      preLoaderRoute: typeof AuthenticatedFinancasVariaveisRouteImport
      parentRoute: typeof AuthenticatedFinancasRoute
    }
    '/_authenticated/financas/fixas': {
      id: '/_authenticated/financas/fixas'
      path: '/fixas'
      fullPath: '/financas/fixas'
      preLoaderRoute: typeof AuthenticatedFinancasFixasRouteImport
      parentRoute: typeof AuthenticatedFinancasRoute
    }
    '/_authenticated/financas/categorias': {
      id: '/_authenticated/financas/categorias'
      path: '/categorias'
      fullPath: '/financas/categorias'
      preLoaderRoute: typeof AuthenticatedFinancasCategoriasRouteImport
      parentRoute: typeof AuthenticatedFinancasRoute
    }
  }
}

interface AuthenticatedFinancasRouteChildren {
  AuthenticatedFinancasCategoriasRoute: typeof AuthenticatedFinancasCategoriasRoute
  AuthenticatedFinancasFixasRoute: typeof AuthenticatedFinancasFixasRoute
  AuthenticatedFinancasVariaveisRoute: typeof AuthenticatedFinancasVariaveisRoute
  AuthenticatedFinancasIndexRoute: typeof AuthenticatedFinancasIndexRoute
}

const AuthenticatedFinancasRouteChildren: AuthenticatedFinancasRouteChildren = {
  AuthenticatedFinancasCategoriasRoute: AuthenticatedFinancasCategoriasRoute,
  AuthenticatedFinancasFixasRoute: AuthenticatedFinancasFixasRoute,
  AuthenticatedFinancasVariaveisRoute: AuthenticatedFinancasVariaveisRoute,
  AuthenticatedFinancasIndexRoute: AuthenticatedFinancasIndexRoute,
}

const AuthenticatedFinancasRouteWithChildren =
  AuthenticatedFinancasRoute._addFileChildren(
    AuthenticatedFinancasRouteChildren,
  )

interface AuthenticatedImobiliarioRouteChildren {
  AuthenticatedImobiliarioConfigRoute: typeof AuthenticatedImobiliarioConfigRoute
  AuthenticatedImobiliarioIndexRoute: typeof AuthenticatedImobiliarioIndexRoute
}

const AuthenticatedImobiliarioRouteChildren: AuthenticatedImobiliarioRouteChildren =
  {
    AuthenticatedImobiliarioConfigRoute: AuthenticatedImobiliarioConfigRoute,
    AuthenticatedImobiliarioIndexRoute: AuthenticatedImobiliarioIndexRoute,
  }

const AuthenticatedImobiliarioRouteWithChildren =
  AuthenticatedImobiliarioRoute._addFileChildren(
    AuthenticatedImobiliarioRouteChildren,
  )

interface AuthenticatedPtRouteChildren {
  AuthenticatedPtClientsRoute: typeof AuthenticatedPtClientsRoute
  AuthenticatedPtPaymentsRoute: typeof AuthenticatedPtPaymentsRoute
  AuthenticatedPtReportsRoute: typeof AuthenticatedPtReportsRoute
  AuthenticatedPtTrainingsRoute: typeof AuthenticatedPtTrainingsRoute
  AuthenticatedPtIndexRoute: typeof AuthenticatedPtIndexRoute
}

const AuthenticatedPtRouteChildren: AuthenticatedPtRouteChildren = {
  AuthenticatedPtClientsRoute: AuthenticatedPtClientsRoute,
  AuthenticatedPtPaymentsRoute: AuthenticatedPtPaymentsRoute,
  AuthenticatedPtReportsRoute: AuthenticatedPtReportsRoute,
  AuthenticatedPtTrainingsRoute: AuthenticatedPtTrainingsRoute,
  AuthenticatedPtIndexRoute: AuthenticatedPtIndexRoute,
}

const AuthenticatedPtRouteWithChildren = AuthenticatedPtRoute._addFileChildren(
  AuthenticatedPtRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedFinancasRoute: typeof AuthenticatedFinancasRouteWithChildren
  AuthenticatedImobiliarioRoute: typeof AuthenticatedImobiliarioRouteWithChildren
  AuthenticatedPtRoute: typeof AuthenticatedPtRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFinancasRoute: AuthenticatedFinancasRouteWithChildren,
  AuthenticatedImobiliarioRoute: AuthenticatedImobiliarioRouteWithChildren,
  AuthenticatedPtRoute: AuthenticatedPtRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicImoveisScrapeRoute: ApiPublicImoveisScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
